dist: bionic
language: python
before_install:
  - pip install -r src/requirements.txt
python:
  - "3.6"

install:
  - make build-spec
  - make -C src build
  - export SPEC_ARTIFACT=`make get-artifact-name`
  - export PYTHON_ARTIFACT=src/`make -s -C src get-artifact-name`
script: ls

deploy:
    provider: releases
    api_key: "$GITHUB_OAUTH_TOKEN"
    file:
      - "$SPEC_ARTIFACT"
      - "$PYTHON_ARTIFACT"
    draft: true
    on:
      branch: feature/python_support
